name: Convert Safari Extension

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Xcode Command Line Tools
      run: |
        xcode-select --install
      # Make sure xcode-select points to the installed version
      env:
        DEVELOPER_DIR: /Library/Developer/CommandLineTools
    - name: Unzip extension
      run: unzip safari-mv3.zip
    - name: Convert to Safari extension
      run: xcrun safari-web-extension-converter ./
    - name: Archive converted extension
      run: |
        cd *"Safari Web Extension"*  # Enter the converted extension folder
        zip -r ../twifiner-safari.zip .
      # Upload the zip as an artifact is optional (replace if needed)
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: converted-extension
      #     path: ../twifiner-safari.zip
