name: Convert Safari Extension

on:
  workflow_dispatch:

jobs:
  build:
    name: Build extensions with bepp
    runs-on: macos-latest # Must be macos for safari extension build
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: pigeonposse/bepp
